-- SBA Data Dictionary: Auth, roles, editable dictionary overrides, and RLS.
-- Run once in Supabase SQL Editor on the sba-datadict-web project.

create type public.app_role as enum ('admin', 'editor', 'viewer');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text not null default '',
  role public.app_role not null default 'viewer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.custom_tables (
  id bigint generated by default as identity primary key,
  name text not null unique,
  thai_name text not null default '',
  description text not null default '',
  created_at timestamptz not null default now()
);

create table public.custom_fields (
  id bigint generated by default as identity primary key,
  table_name text not null,
  name text not null,
  data_type text not null default '',
  key_name text not null default '',
  description text not null default '',
  business_rule text not null default '',
  created_at timestamptz not null default now(),
  unique (table_name, name)
);

create table public.table_overrides (
  table_name text primary key,
  thai_name text not null default '',
  description text not null default '',
  updated_at timestamptz not null default now()
);

create table public.field_overrides (
  table_name text not null,
  field_name text not null,
  data_type text not null default '',
  key_name text not null default '',
  description text not null default '',
  business_rule text not null default '',
  updated_at timestamptz not null default now(),
  primary key (table_name, field_name)
);

create table public.deleted_tables (
  table_name text primary key,
  deleted_at timestamptz not null default now()
);

create table public.deleted_fields (
  table_name text not null,
  field_name text not null,
  deleted_at timestamptz not null default now(),
  primary key (table_name, field_name)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  assigned_role public.app_role;
begin
  if not exists (select 1 from public.profiles) then
    assigned_role := 'admin';
  else
    assigned_role := 'viewer';
  end if;

  insert into public.profiles (id, email, display_name, role)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email, ''), '@', 1)),
    assigned_role
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_user_role()
returns public.app_role
language sql
stable
security definer
set search_path = ''
as $$
  select role from public.profiles where id = (select auth.uid());
$$;

create or replace function public.set_user_role_by_email(target_email text, new_role public.app_role)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if public.current_user_role() <> 'admin' then
    raise exception 'Admin permission required';
  end if;
  update public.profiles
  set role = new_role, updated_at = now()
  where lower(email) = lower(target_email);
  return found;
end;
$$;

revoke all on function public.set_user_role_by_email(text, public.app_role) from public;
grant execute on function public.set_user_role_by_email(text, public.app_role) to authenticated;

alter table public.profiles enable row level security;
alter table public.custom_tables enable row level security;
alter table public.custom_fields enable row level security;
alter table public.table_overrides enable row level security;
alter table public.field_overrides enable row level security;
alter table public.deleted_tables enable row level security;
alter table public.deleted_fields enable row level security;

create policy "profiles read self or admin"
on public.profiles for select to authenticated
using (id = (select auth.uid()) or public.current_user_role() = 'admin');

create policy "dictionary public read"
on public.custom_tables for select to anon, authenticated using (true);
create policy "dictionary public read"
on public.custom_fields for select to anon, authenticated using (true);
create policy "dictionary public read"
on public.table_overrides for select to anon, authenticated using (true);
create policy "dictionary public read"
on public.field_overrides for select to anon, authenticated using (true);
create policy "dictionary public read"
on public.deleted_tables for select to anon, authenticated using (true);
create policy "dictionary public read"
on public.deleted_fields for select to anon, authenticated using (true);

create policy "editors manage dictionary"
on public.custom_tables for all to authenticated
using (public.current_user_role() in ('admin', 'editor'))
with check (public.current_user_role() in ('admin', 'editor'));
create policy "editors manage dictionary"
on public.custom_fields for all to authenticated
using (public.current_user_role() in ('admin', 'editor'))
with check (public.current_user_role() in ('admin', 'editor'));
create policy "editors manage dictionary"
on public.table_overrides for all to authenticated
using (public.current_user_role() in ('admin', 'editor'))
with check (public.current_user_role() in ('admin', 'editor'));
create policy "editors manage dictionary"
on public.field_overrides for all to authenticated
using (public.current_user_role() in ('admin', 'editor'))
with check (public.current_user_role() in ('admin', 'editor'));
create policy "editors manage dictionary"
on public.deleted_tables for all to authenticated
using (public.current_user_role() in ('admin', 'editor'))
with check (public.current_user_role() in ('admin', 'editor'));
create policy "editors manage dictionary"
on public.deleted_fields for all to authenticated
using (public.current_user_role() in ('admin', 'editor'))
with check (public.current_user_role() in ('admin', 'editor'));
